// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wakshuxcxvmgqhmbdpgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indha3NodXhjeHZtZ3FobWJkcGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODk5ODgsImV4cCI6MjA2Njg2NTk4OH0.mz0IcjRzeTKSz8yqZYiDQ3yKUTYuRLEm5bh09TzixsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});